### ISSUE TITLE
Save Image causes shutdown on iPhone SE

### ISSUE THREAD

**Issue by ingfabby** [OnionBrowser/iOS-OnionBrowser#191] opened 2019-06-05 19:56 UTC
Reported after the last release on May 21, 2019, on the Apple app store.

**Comment by tladesignz** [comment] 2019-06-14 11:11
I can't reproduce this. However, I have an idea: The image unfortunately needs to be re-downloaded, despite having done so already. This is done in the foreground thread which therefore freezes the UI, when the image is bigger and/or the device is slower. 

Maybe that's what caused a freeze, which made the user think it got shutdown. Or some system watchdog actually came by and really killed the app, due to rendering the device unusable.

For further background read issue #10. We're really stuck here, due to serious system limitations. If we get more reports like that, we actually need to remove that feature.

Doing this "store x on my device" feature right would actually require to implement a full-fledged HTTP proxy or something which comes pretty close to it, it seems at the current time.

**Comment by r3ckd** [comment] 2019-10-21 16:20
Does the work we did fixing OCSP #178 have any possible impact here?

**Comment by tladesignz** [comment] 2019-10-22 09:18
Oh, hell, yes! Thanks for the remainder!

Actually, this should be fixed by f30f3b2!

**Closed as completed by tladesignz** 2019-10-22 09:18 UTC
Labels: bug, feedback
