### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by 7ife** [OnionBrowser/iOS-OnionBrowser#373] opened 2022-02-26 04:48 UTC
in the last update, you improved the icon for the worse, white stripes are visible on the edges on a dark background

**Comment by tladesignz** [comment] 2022-03-01 12:12
Duplicate of #364.
Anyway, thanks for mentioning it again. I missed to fix one icon - which is the exact one used on the app store. :-/ Will be fixed on next release.

**Closed as completed by tladesignz** 2022-03-01 12:12 UTC
