### ISSUE TITLE
Can't search with DuckDuckGo Onion

### ISSUE THREAD

**Issue by MarkCallow** [OnionBrowser/iOS-OnionBrowser#150] opened 2018-09-27 01:35 UTC
Tapping the DuckDuckGo .onion link in the bookmarks successfully takes you to the DDG search page but enter anything in the search field and tap the magnifying glass and all you get is a page that is empty but for the word "forbidden" in the top left corner.

This is 100% reproducible.  DDG .onion works fine in TorBrowser which is why I am reporting the problem here rather than to DDG.

**Comment by tladesignz** [comment] 2019-03-05 12:47
Sorry, I can't reproduce this. Not with the currently live version (2.1.0) nor with the latest master which will soon be released as 2.2.0.

It could be, that DDG blocks certain exit nodes, due to abusive behaviour by them. (Could even be unrelated to Tor). 

Try to get different ones by restarting the app, that's the only advice I can give a.t.m.

Maybe it gets better with the new release coming soon, as that will contain a newer Tor version. But that could just be wishful thinking. :-)

**Closed as completed by tladesignz** 2019-03-05 12:47 UTC
