### ISSUE TITLE
Crash captcha 

### ISSUE THREAD

**Issue by Aecco** [OnionBrowser/iOS-OnionBrowser#352] opened 2021-09-10 23:36 UTC
The application crashes in some cases when pasting from the clipboard to a site with a 2fa captcha. On some forums, chats do not load, it only allows you to refresh the page ( I opened a list of divlogs-updated, selected the necessary divlog-updated, etc. ) Only after that messages appear. Version 2.7.5

**Comment by tladesignz** [comment] 2021-09-15 07:49
Sorry, but without links to test, we're unable to reproduce any of this and therefore can't research the root cause. If you want to provide some, I'm happy to look into this, if not, I'll close this the next time I come by here.

**Comment by tladesignz** [comment] 2021-10-06 09:38
Closed for inactivity.

**Closed as completed by tladesignz** 2021-10-06 09:38 UTC
