### ISSUE TITLE
Attribute framename in tag target

### ISSUE THREAD

**Issue by 7ife** [OnionBrowser/iOS-OnionBrowser#319] opened 2021-03-23 06:05 UTC
It doesn’t work in <iframe> For IOS  14.4

**Comment by tladesignz** [comment] 2021-03-23 10:12
Sorry, I don't think I fully understand your problem. Can you get more precise?

Please note, though: *All* iOS apps which render webpages are using either of two system-provided renderers: `UIWebView` or `WKWebView`. 

The first is being out-phased by Apple, so when web page rendering suddenly breaks with iOS updates, that's a problem caused by Apple which we probably can't fix and which Apple probably won't fix any more, Because of the out-phasing.

Unfortunately, we currently can't migrate to `WKWebView` which is more modern and probably doesn't have that problem. You can find more about why e.g. here: #47

**Comment by 7ife** [comment] 2021-03-23 15:58
Just go to the demo of [my chats](https://7ife.github.io/cbdemo-0/), through safari just in ios 14.4 click on the emoji button (for example) it will open in the chat window, now go through the tor browser and do the same. Checked on iOS 12.5.1 Tor browser works well.

**Comment by tladesignz** [comment] 2021-03-29 15:52
Aaaah, now I get it. Thanks for catching this! This was our Universal Link Protection feature interfering.

As a workaround until a new release is out, you can switch that off, then it'll work.

**Closed as completed by tladesignz** 2021-03-29 15:52 UTC
