### ISSUE TITLE
Toolbar overlap

### ISSUE THREAD

**Issue by ingfabby** [OnionBrowser/iOS-OnionBrowser#193] opened 2019-06-05 20:12 UTC
I had to move the toolbar down to the bottom because it overlaps with the top status bar of the iPad (time, battery indicators, etc.). It is really difficult to have it respond to tap when the toolbar is conflicting with the iOS status line at the top.

**Comment by tladesignz** [comment] 2019-06-14 09:35
I did some quick testing with different iOS versions (11.4 and 12.2 - the ones we currently support) and different devices (iPad mini 2, iPad Pro 11" and iPad 5th gen) and couldn't reproduce with our latest version.

However, there's a commit f38a03087b0ffd4d8b369192e5765e2169aacc84, which fixes issue #169  and was already released with version 2.2.1. Could it be that somebody is lagging behind? Maybe trying to install on older iOS version, which we don't support anymore, and therefore getting an older version which still contains this problem?

**Comment by tladesignz** [comment] 2019-10-24 14:24
Will be fixed with #210 UI redesign.

**Closed as completed by tladesignz** 2019-10-24 14:24 UTC
Labels: bug, feedback
