### ISSUE TITLE
What websites do you use that are not functional under Onion Browser? 

### ISSUE THREAD

**Issue by kilo6eight** [OnionBrowser/iOS-OnionBrowser#260] opened 2020-04-04 21:39 UTC
Please use this threat to post feedback to developers about websites that are not properly functional under Onion Browser due to the browser (not the Tor network). 

1. Twitter / Tweetdeck - playing videos, unable opening tweets in new tabs. 
2. Standard Notes - editing notes, changing templates.

**Comment by tladesignz** [comment] 2020-04-06 09:45
> playing videos

Videos can't be played on anything the security level "insecure" (or "bronze" as per upcoming version 2.6.0). That's because due to limitations of iOS: videos bypass Tor. If you're behind a censoring WiFi network/ISP/country, you may never see videos because of that fact.

> unable opening tweets in new tabs.

Is that an inherent feature of the website (i.e. is there JavaScript trying to open a new tab?) or do you mean by long-tapping a link and choosing to open in a new tab?

> 2. Standard Notes - editing notes, changing templates.

Sorry, you may assume that Twitter is common knowledge, but "Standard Notes"? Please provide links and in-depth descriptions of what needs to be done to invoke the problem.

**Comment by Ju012** [comment] 2020-05-31 17:40
![IMG_0003](https://user-images.githubusercontent.com/63131886/83358813-185be280-a344-11ea-86ad-a028cb5a5725.PNG)

Some sites have an SSL error on obfs4 or custom bridges. I haven’t tested this on meek-azure as of yet.

**Comment by tladesignz** [comment] 2020-06-05 11:09
> Some sites have an SSL error on obfs4 or custom bridges. I haven’t tested this on meek-azure as of yet.

Sorry, can't reproduce this problem. 

Since anybody can contribute servers and bandwidth to the Tor network, there's of course also adversarial organizations in it. You might have come across a bridge which tries strange things. Could just be a security researcher from a university, or some country's intelligence service trying stuff.

E.g. this looks like a TLS downgrade attack. You could play with the accepted TLS version settings to have it go away (, but be vunerable, then). Although, it could be, that you did just that. On the other hand, I could set OB to accept TLS 1.3 only and still access howtogeek.com.

I see from your screenshot, that you're running through a VPN. That could also be the culprit, of course.

I guess for the Tor Project, it would be interesting, if you report proxies to them, which behave strange. But please reproduce this on Tor Browser Desktop first, and without any VPN!

**Comment by tladesignz** [comment] 2020-06-16 14:49
Ok, I close this. Feel free to reopen, if you come up with new insights!

**Closed as completed by tladesignz** 2020-06-16 14:49 UTC
