### ISSUE TITLE
Tor client does not restarts after app awakes

### ISSUE THREAD

**Issue by umairali332** [OnionBrowser/iOS-OnionBrowser#59] opened 2015-03-27 11:37 UTC
If I lock the device while Onion Browser application is running or in background and unlock device and launch the application it stops working. It shows an alert to exit the application. 

Whereas there are some applications which use tor client but they don't have this behaviour. They sleep and awake successfully and start working without restarting. For example tor browser free iOS application. Can this behaviour be achieved in this application sooner or later?

**Comment by RustamDz** [comment] 2015-09-22 13:47
That's because code in TorController.m:
- (void)appDidBecomeActive {
    if (![_mSocket isConnected]) {
        #ifdef DEBUG
        NSLog(@"[tor] Came back from background, sending HUP" );
        #endif
        [_mSocket writeString:@"SIGNAL HUP\n" encoding:NSUTF8StringEncoding];
        _torCheckLoopTimer = [NSTimer scheduledTimerWithTimeInterval:0.25f
                                                              target:self
                                                            selector:@selector(activateTorCheckLoop)
                                                            userInfo:nil
                                                             repeats:NO];
    }
}
We trying to send HUP to not connected socket and doing nothing with connected.

**Comment by mtigas** [comment] 2015-10-30 22:50
@RustamDz THANK YOU for pointing out that mistake (i.e. that `activateTorCheckLoop` should be activated regardless of if `[_mSocket isConnected]`; only the HUP needs to be sent if not connected). I’m certain that this causes a lot of the grief regarding backgrounding in the app.

(Closing this, as it’s technically a dupe of #2.)

**Closed by mtigas** 2015-10-30 22:50 UTC
