### ISSUE TITLE
Backgrounding during startup ensures no connection

### ISSUE THREAD

**Issue by DanGould** [OnionBrowser/iOS-OnionBrowser#294] opened 2020-09-27 17:27 UTC
To reproduce:

1) open OnionBrowser
2) quickly go home either by home button or swipe up to send OnionBrowser to background
3) re-open OnionBrowser to foreground
4) watch the app get stuck on the "Connecting to Tor" screen. the app is now stuck in this state

-

I think the bug is that[ the experimental Tor shutdown](https://github.com/OnionBrowser/OnionBrowser/blob/860d001712d5c80108f64c658e8927f0fcbca1bb/OnionBrowser/OnionManager.swift#L444-L461) does not actually exit the TORThread, but only signals to cancel without listening for IsCancelled and then performing an Exit (like https://stackoverflow.com/questions/5193062/how-to-stop-nsthread suggests).

Is there a reason we can't keep the torThread referenced without cancelling? Does anyone have a better idea of why this happens during init but not after init?

**Comment by tladesignz** [comment] 2020-09-27 19:20
Huh? Sorry, your double-negating question is quite hard to understand.

The thing is, we can't choose how long we are going to stay alive. The app (incl. the Tor thread) just won't get any more processing time after a few seconds.

The only chance we get is to tell Tor to stop, when we get the signal that we're going to be suspended.

I guess, it's just not listening in certain phases in startup, or takes too long to actually shut down.

Tor was designed with the idea in mind, that it runs in its own process. That's just not possible on iOS. We need to run it in a thread and a thread can't be force-stopped from other threads, because of shared memory. (It's unclear, which memory could be given up from the outside.) You can send a `cancel` message to a `NSThread` but its up to the thread to actually do something about it. It actually needs to check the `isCancelled` flag, when it deems fit. Since Tor is written in `C`, it doesn't now about being wrapped in a `NSThread`, therefore doesn't check a `isCancelled` flag.

Anyway, the good folks at the Tor Project are so nice to retrofit Tor to be able to work in a thread: They improved the cleanup a lot in the last 2 years. However, with the original design, there are obviously edge cases (like the one you stumbled over), where its not working very good, yet.

I will point a Tor member to have a look at this, maybe they can find some easy wins. But I won't put too much pressure on this, because we're currently working on more important stuff. (Like have Tor work on iOS after iOS 14.)

@ahf, can you please have a look at this and maybe find some ways to improve?

**Comment by DanGould** [comment] 2020-09-27 19:56
Thank you Benjamin for the thorough response. I appreciate what is being done here is cutting edge and that the framework is a careful retrofit with an abundance of limitations we must work around.

> Is there a reason we can't keep the torThread referenced without cancelling?

https://github.com/OnionBrowser/OnionBrowser/blob/860d001712d5c80108f64c658e8927f0fcbca1bb/OnionBrowser/OnionManager.swift#L444-L461

From my limited understanding in the above bit of code, the `torThread` is set to `nil`. This means when we check if `torThread?.IsCancelled` during `startTor`  we mistakenly initializing another `TORThread` for which there can only be one per process causing failure. Because `torThread == nil` but the actual thread did not exit. Looks like a place to start to me.

p.s. I've defiled Tor further by binding Tor.Framework to C# so we can conduct Bitcoin CoinJoins on iOS over Tor with Wasabi wallet which is how I came across this problem and ultimately my motivation for fixing it

**Comment by tladesignz** [comment] 2020-09-28 07:43
> From my limited understanding in the above bit of code, the torThread is set to nil. This means when we check if torThread?.IsCancelled during startTor we mistakenly initializing another TORThread for which there can only be one per process causing failure. Because torThread == nil but the actual thread did not exit. Looks like a place to start to me.

That's the check:

https://github.com/OnionBrowser/OnionBrowser/blob/860d001712d5c80108f64c658e8927f0fcbca1bb/OnionBrowser/OnionManager.swift#L241

So, after doing 

https://github.com/OnionBrowser/OnionBrowser/blob/860d001712d5c80108f64c658e8927f0fcbca1bb/OnionBrowser/OnionManager.swift#L457

having a nil `torThread` is equivalent to having a cancelled `torThread`.

Sorry, but: forget this. All the `NSThread` mangling is just cosmetics. It's just about releasing the reference to make sure, *we're* not holding onto code any longer, we don't want to. Tor doesn't car about it **at all**.

It's completely up to Tor to finish properly.

However, all your insisting gives me ideas. On `#startTor`, we could first try to connect to Tors control port and see in which state it is. If it's still usable, just use it. However unclear now, what to do with the reference to the Tor thread. Keep it? Try to find it again? Is it actually needed at all? Needs some more research. Could also lead to more bugs, when finding Tor in a completely broken state. And then what? The only thing to reset properly is to kill the app and ask the user to start us again. Not a great improvement.

**Comment by ahf** [comment] 2020-10-01 23:14
I'll take a look.

**Comment by tladesignz** [comment] 2022-02-21 13:10
This is quite old and we still don't have a good solution. I'll close this now. Feel free to reopen, if any new insights arise.

**Closed as completed by tladesignz** 2022-02-21 13:10 UTC
