### ISSUE TITLE
Can't download files from onion service

### ISSUE THREAD

**Issue by jjsp556** [OnionBrowser/iOS-OnionBrowser#293] opened 2020-09-24 17:22 UTC
Downloading files from a hidden service does not seem to work on version 2.6.2 on iOS 14. Navigating to flibustahezeous3.onion/b/151260/epub simply shows a screen with the file name, type, and size. When trying to save the file to Files or Books via the Share Sheet, nothing happens. 

> It doesn't work for me yet (using 2.2.1 available in iOS AppStore).
> 
> Reproduce: paste this url http://flibustahezeous3.onion/b/151260/epub to Onion Browser search bar.
> 
> Expected: an EPUB file named `Lukyanenko_Genom_1_Genom.151260.fb2.epub` should download (as it does in Tor browser desktop) and a choice is offered to save it to iOS Files app or open it in Books app (or whatever is the default behaviour in e.g. Safari mobile when downloading files).
> 
> Observed: literally nothing happens.
> 
> _Originally posted by @ikonkere in https://github.com/OnionBrowser/OnionBrowser/issues/10#issuecomment-565438747_

**Comment by ikonkere** [comment] 2020-09-24 17:50
Can confirm, nothing happens using Share screen on my iPhone with iOS 14 as well. #10 

UPDATE. You can actually use "Copy" action from Share screen and the file copies and can be pasted in Files app :). This can be used as workaround until the regression is fixed.

It seems the file is _downloaded_, but for whatever reason can't be _saved_ via app integration (tried both Files and Dropbox).

**Comment by jjsp556** [comment] 2020-09-24 20:33
> Can confirm, nothing happens using Share screen on my iPhone with iOS 14 as well. #10
> 
> UPDATE. You can actually use "Copy" action from Share screen and the file copies and can be pasted in Files app :). This can be used as workaround until the regression is fixed.
> 
> It seems the file is _downloaded_, but for whatever reason can't be _saved_ via app integration (tried both Files and Dropbox).

This workaround does not seem to work for me. I go to a hidden service file link, and the page describing the file name, type, and size comes up. I then open the share sheet and select "Copy". I then go the the Files app, but there is no UI option to "paste" the file in that I can find. 

UPDATE: Never mind! I found that I had to be in a directory in the Files app to paste the file in, and it works. Thanks for the tip!

**Comment by tladesignz** [comment] 2020-09-24 20:49
Wow. Didn't expect that feature to be so critical. Please relax for a bit. This very much reads like a duplicate of #292, which I fixed last week. Currently in beta testing, will be released soon. PM me, if you want to be on the beta.

**Closed as completed by tladesignz** 2020-09-24 20:49 UTC

**Comment by richardcfirth** [comment] 2020-10-06 19:48
How do we get in on the TestFlight beta?

**Comment by tladesignz** [comment] 2020-10-07 09:06
> How do we get in on the TestFlight beta?

Version 2.7.0 is released since a few days. Currently no beta.

PM me, then I'll provide a TestFlight link. Follow my GitHub profile to find various means of contacting me.
